name: location_example
description: Demonstrates how to use the location plugin.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  curved_navigation_bar: ^0.3.2
  google_maps_flutter: ^0.5.28+1
  page_transition: ^1.0.9
  material_design_icons_flutter: ^4.0.5145

  geocoder: ^0.2.1
  location: ^3.0.2
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.1

flutter:
  uses-material-design: true
assets:
  - point.png 
